import { scrypt, randomBytes, timingSafeEqual, createHmac } from "node:crypto";

// Everything here uses node:crypto — no auth dependency needed for a single
// admin account. Credentials live in env vars, never in the repo and never in
// anything the browser can read.
const ADMIN_EMAIL = (process.env.ADMIN_EMAIL || "").trim().toLowerCase();
const ADMIN_PASSWORD_HASH = process.env.ADMIN_PASSWORD_HASH || "";
const SESSION_SECRET = process.env.SESSION_SECRET || "";
const COOKIE_NAME = "roi_admin";
const SESSION_HOURS = 12;

export const authConfigured = Boolean(ADMIN_EMAIL && ADMIN_PASSWORD_HASH && SESSION_SECRET);

function scryptAsync(password, salt, keylen) {
  return new Promise((resolve, reject) => {
    scrypt(password, salt, keylen, (err, derived) => (err ? reject(err) : resolve(derived)));
  });
}

// Format: scrypt$<saltHex>$<keyHex>. Generated by scripts/hash-password.mjs.
export async function hashPassword(password) {
  const salt = randomBytes(16);
  const key = await scryptAsync(password, salt, 64);
  return `scrypt$${salt.toString("hex")}$${key.toString("hex")}`;
}

export async function verifyPassword(password, stored) {
  const parts = String(stored).split("$");
  if (parts.length !== 3 || parts[0] !== "scrypt") return false;
  const salt = Buffer.from(parts[1], "hex");
  const expected = Buffer.from(parts[2], "hex");
  const actual = await scryptAsync(password, salt, expected.length);
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

const b64url = (buf) => Buffer.from(buf).toString("base64url");

function sign(payloadB64) {
  return createHmac("sha256", SESSION_SECRET).update(payloadB64).digest("base64url");
}

export function issueSession(email) {
  const payload = { email, exp: Date.now() + SESSION_HOURS * 3600 * 1000 };
  const payloadB64 = b64url(JSON.stringify(payload));
  return `${payloadB64}.${sign(payloadB64)}`;
}

export function readSession(token) {
  if (!token || typeof token !== "string") return null;
  const [payloadB64, sig] = token.split(".");
  if (!payloadB64 || !sig) return null;
  const expected = sign(payloadB64);
  // compare as buffers of equal length, or timingSafeEqual throws
  const a = Buffer.from(sig);
  const b = Buffer.from(expected);
  if (a.length !== b.length || !timingSafeEqual(a, b)) return null;
  try {
    const payload = JSON.parse(Buffer.from(payloadB64, "base64url").toString("utf8"));
    if (!payload.exp || Date.now() > payload.exp) return null;
    return payload;
  } catch {
    return null;
  }
}

function parseCookies(header) {
  const out = {};
  String(header || "").split(";").forEach((part) => {
    const i = part.indexOf("=");
    if (i > -1) out[part.slice(0, i).trim()] = decodeURIComponent(part.slice(i + 1).trim());
  });
  return out;
}

export function sessionCookie(token) {
  const maxAge = SESSION_HOURS * 3600;
  return `${COOKIE_NAME}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
}

export function clearCookie() {
  return `${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`;
}

export function currentUser(req) {
  if (!authConfigured) return null;
  return readSession(parseCookies(req.headers.cookie)[COOKIE_NAME]);
}

// Wrap a handler so it only runs for a signed-in admin.
export function requireAuth(handler) {
  return async (req, res) => {
    if (!authConfigured) {
      return res.status(503).json({ error: "Admin auth is not configured. Set ADMIN_EMAIL, ADMIN_PASSWORD_HASH and SESSION_SECRET." });
    }
    const user = currentUser(req);
    if (!user) return res.status(401).json({ error: "Not signed in." });
    return handler(req, res, user);
  };
}

export { ADMIN_EMAIL, COOKIE_NAME };
